Save to output of SHOW ALL to pg_settings_DATETIME.out

diff --git a/pg_back b/pg_back
--- a/pg_back
+++ b/pg_back
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright 2011-2018 Nicolas Thauvin and contributors. All rights
+# Copyright 2011-2020 Nicolas Thauvin and contributors. All rights
 # reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -268,6 +268,17 @@ else
     dumped+=( "pg_global" )
 fi
 
+# Dump configuration using SHOW ALL
+dump="$PGBK_BACKUP_DIR/pg_settings_${DUMP_DATE}.out"
+info "saving output of SHOW ALL to ${dump}"
+${PGBK_BIN}psql -X -o "${dump}" -c "SHOW ALL;" $PGBK_CONNDB
+if [ $? != 0 ]; then
+    error "psql -c 'SHOW ALL' failed"
+    out_rc=1
+else
+    dumped+=( "pg_settings" )
+fi
+
 # Dump database
 for db in $PGBK_DBLIST
 do
@@ -330,7 +341,7 @@ else
         # with the time of last modification since Epoch. Sort them so
         # that the newest come first and keep
         to_purge=()
-        for t in dump sql ${SIGNATURE_ALGO}; do
+        for t in dump sql ${SIGNATURE_ALGO} out; do
             i=1
             while read line; do
                 if (( $i > ${PGBK_PURGE_MIN_KEEP:-0} )); then
