Timeout on pause attempt to prevent multiple executions
A long query with AccessShareLock on master will be replicated,
and will cause an internal loop when invoking pg_back on standby.
To prevent multiple executions of pg_back on daily routine, this
introduces a new option PGBK_PAUSE_TIMEOUT (-T) that waits an amount
of time in seconds before dying.

The pause/resume replay logic has been simplified.

diff --git a/pg_back b/pg_back
--- a/pg_back
+++ b/pg_back
@@ -36,6 +36,7 @@ PGBK_PURGE=30
 PGBK_PURGE_MIN_KEEP=0
 PGBK_OPTS="-Fc"
 PGBK_WITH_TEMPLATES="no"
+PGBK_PAUSE_TIMEOUT=3600
 PGBK_CONNDB="postgres"
 SIGNATURE_ALGO="none"
 
@@ -52,6 +53,7 @@ usage() {
     echo "                everything (default: \"$PGBK_PURGE_MIN_KEEP\")"
     echo "  -D db1,...    list of databases to exclude"
     echo "  -t            include templates"
+    echo "  -T timeout    seconds of pausing attempt (default: \"$PGBK_PAUSE_TIMEOUT\")"
     echo
     echo "  -h hostname   database server host or socket directory (default: \"${PGHOST:-local socket}\")"
     echo "  -p port       database server port (default: \"$PGPORT\")"
@@ -92,7 +94,7 @@ warn() {
 [ -f "$PGBK_CONFIG" ] || PGBK_CONFIG="/etc/postgresql/pg_back.conf"
 
 # Process command line
-args=`getopt "b:c:P:K:D:th:p:S:U:d:qV?" $*`
+args=`getopt "b:c:P:K:D:T:th:p:S:U:d:qV?" $*`
 if [ $? -ne 0 ]
 then
     usage 2
@@ -109,6 +111,7 @@ do
 	-K) CLI_PURGE_MIN_KEEP=$2; shift 2;;
 	-D) CLI_EXCLUDE="`echo $2 | tr ',' ' '`"; shift 2;;
 	-t) CLI_WITH_TEMPLATES="yes"; shift;;
+    -T) CLI_PAUSE_TIMEOUT=$2; shift 2;;
 	-h) CLI_HOSTNAME=$2; shift 2;;
 	-p) CLI_PORT=$2; shift 2;;
 	-d) CLI_CONNDB=$2; shift 2;;
@@ -137,6 +140,7 @@ fi
 [ -n "$CLI_PURGE_MIN_KEEP" ] && PGBK_PURGE_MIN_KEEP=$CLI_PURGE_MIN_KEEP
 [ -n "$CLI_EXCLUDE" ] && PGBK_EXCLUDE=$CLI_EXCLUDE
 [ -n "$CLI_WITH_TEMPLATES" ] && PGBK_WITH_TEMPLATES=$CLI_WITH_TEMPLATES
+[ -n "$CLI_PAUSE_TIMEOUT" ] && PGBK_PAUSE_TIMEOUT=$CLI_PAUSE_TIMEOUT
 [ -n "$CLI_HOSTNAME" ] && PGBK_HOSTNAME=$CLI_HOSTNAME
 [ -n "$CLI_PORT" ] && PGBK_PORT=$CLI_PORT
 [ -n "$CLI_USERNAME" ] && PGBK_USERNAME=$CLI_USERNAME
@@ -164,6 +168,7 @@ info "preparing to dump"
 if [[ $PGBK_PURGE_MIN_KEEP != "all" ]]; then
     [[ $PGBK_PURGE_MIN_KEEP =~ ^[[:digit:]]+$ ]] || die "PGBK_PURGE_MIN_KEEP (-K) '$PGBK_PURGE_MIN_KEEP' is not an integer"
 fi
+[[ $PGBK_PAUSE_TIMEOUT =~ ^[[:digit:]]+$ ]] || die "PGBK_PAUSE_TIMEOUT (-T) '$PGBK_PAUSE_TIMEOUT' is not an integer"
 
 # Ensure there is a trailing slash in the path to the binaries
 if [ -n "$PGBK_BIN" ]; then
@@ -218,25 +223,29 @@ if [ "${PG_HASPAUSE}" = "1" ]; then
     # pausing the replication replay
     typeset -i PGBK_EXCLLOCKS;
     PGBK_EXCLLOCKS=1;
-    while [ $PGBK_EXCLLOCKS -gt 0  ]
+    PGBK_PAUSE=10
+    while [ $PGBK_EXCLLOCKS -gt 0 ]
     do
-        ${PGBK_BIN}psql -X $OPTS -At -c "SELECT pg_${xlog_or_wal}_replay_pause() where pg_is_in_recovery();" $PGBK_CONNDB
-        if [ $? != 0 ]; then
-            die "could not pause replication replay"
-        fi
         PGBK_EXCLLOCKS=`${PGBK_BIN}psql -X $OPTS -At -c "SELECT count(*) FROM pg_locks WHERE mode = 'AccessExclusiveLock';" $PGBK_CONNDB`
         if [ $? != 0 ]; then
             die "could not get lock information"
         fi
+        
         if [ $PGBK_EXCLLOCKS -gt 0 ]; then
-            ${PGBK_BIN}psql -X $OPTS -At -c "SELECT pg_${xlog_or_wal}_replay_resume();" $PGBK_CONNDB
-            if [ $? != 0 ]; then
-                die "could not resume replication replay"
+            if [ $PGBK_PAUSE_TIMEOUT -le 0 ]; then
+                die "attemp to pause replication exceeds timeout"
             fi
-	    echo "The slave database has exclusive locks (vacuum full, truncate or other locking command) running on master"
-        echo "Resuming replication for 10s"
-        sleep 10
-	fi
+
+            echo "The slave database has exclusive locks (vacuum full, truncate or other locking command) running on master"
+            echo "Resuming replication for ${PGBK_PAUSE}s"
+            let "PGBK_PAUSE_TIMEOUT-=$PGBK_PAUSE"
+            sleep $PGBK_PAUSE
+        else
+            ${PGBK_BIN}psql -X $OPTS -At -c "SELECT pg_${xlog_or_wal}_replay_pause() where pg_is_in_recovery();" $PGBK_CONNDB
+            if [ $? != 0 ]; then
+                die "could not pause replication replay"
+            fi
+        fi
     done
 fi
 
